### ISSUE TITLE
getContentVersionBody

### ISSUE THREAD

**Issue by CalebEverett** [kevinohara80/nforce#107]
https://github.com/kevinohara80/nforce/blob/master/index.js#L590

This is '/versiondata' now instead of '/body'. I'm happy to try to put a pull request together. Do you want to keep the name of the method the same or change it out to "getContentVersionData"?

**Comment by kevinohara80** [comment]
Did you find this change in the docs somewhere? I know that the `/body` uri worked in the past.

I guess I'd prefer to add the `getContentVersionData()` method for now and find out if the body URI is, in fact deprecated and deprecate the `getContentVersionBody()` method.

Go ahead and add a `getContentVersionData()` method. That'd be great.

**Comment by CalebEverett** [comment]
Will do, here's the link to the doc

https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_contentversion.htm

Did you find this change in the docs somewhere? I know that the /body uri
worked in the past.

I guess I'd prefer to add the getContentVersionData() method for now and
find out if the body URI is, in fact deprecated and deprecate the
getContentVersionBody() method.

Go ahead and add a getContentVersionData() method. That'd be great.

—
Reply to this email directly or view it on GitHub
<https://github.com/kevinohara80/nforce/issues/107#issuecomment-180871834>.
