### ISSUE TITLE
Create arbitrary POST request

### ISSUE THREAD

**Issue by pchittum** [kevinohara80/nforce#110]
As the salesforce api continues to expand, it might be useful to create a way for nforce to make an arbitrary POST request while waiting for specific features to be supported. 

Use Case: POST to generic streaming API channel. 

This requires making an HTTP POST request to 

/services/data/v36.0/sobjects/StreamingChannel/{channelId}/push

(where {channelId} is the salesforce ID for the generic channel). 

I was able to get this to work, but I ended up using the should-be-private `_apiRequest` method. I would much rather have a way to make a POST pre-packaged in the same way that `getUrl` is made available for arbitrary HTTP GET requests. 

I am crazy busy for the next month. If I can get back to this later, I might have a stab and make a PR. But if I post this here, maybe someone else will have a go first. 

Thanks! Great lib, by the way!

**Comment by afawcett** [comment]
+1 for this, looking to be able invoke a Flow via https://developer.salesforce.com/docs/atlas.en-us.salesforce_vpm_guide.meta/salesforce_vpm_guide/vpm_distribute_system_rest.htm

**Comment by kevinohara80** [comment]
@pchittum @afawcett I've got vacation next week so I could probably add this...unless someone else wants to submit the PR. :)

**Comment by pchittum** [comment]
I won't have time for anything for while. If I find time Ineillcheck with
you before I dive in.

On Friday, 3 June 2016, kevinohara80 <notifications@github.com> wrote:

> @pchittum <https://github.com/pchittum> @afawcett
> <https://github.com/afawcett> I've got vacation next week so I could
> probably add this...unless someone else wants to submit the PR. :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kevinohara80/nforce/issues/110#issuecomment-223624250>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABE1xKpJK1uERrxoqvCj9eWcdlb349plks5qIFPXgaJpZM4HjvUy>
> .
>


-- 
Peter Chittum
Director, Developer Evangelism EMEA
+44 7786 515 531
@pchittum
Sent from Gmail Mobile

**Comment by jkentjnr** [comment]
@afawcett I created https://github.com/jkentjnr/nforce-actions and have only added support to date for flows:

**Comment by afawcett** [comment]
Nice thanks @jkentjnr

**Comment by kevinohara80** [comment]
I also added more low-level REST methods in v1.10.
