### ISSUE TITLE
Error on streaming disconnect

### ISSUE THREAD

**Issue by kgowru** [kevinohara80/nforce#112]
App crashing when I close the streaming connection after a timeout. 

App Code: 

     timeoutId = setTimeout(function(){        
           accs.cancel();
           client.disconnect();
           console.log('killed long-poll');
           res.end();
     }, 300000);

Error:
Mar 02 11:05:17 app/web.1:  /app/node_modules/nforce/node_modules/faye/node/faye-node.js:1568 
Mar 02 11:05:17 heroku/web.1:  State changed from crashed to starting 
Mar 02 11:05:17 app/web.1:      envelope.request = this._transport.sendMessage(message); 
Mar 02 11:05:17 app/web.1:                                        ^ 
Mar 02 11:05:17 app/web.1:  TypeError: Cannot read property 'sendMessage' of undefined 
Mar 02 11:05:17 app/web.1:      at Object.Faye.Dispatcher.Faye.Class._sendEnvelope (/app/node_modules/nforce/node_modules/faye/node/faye-node.js:1568:39) 
Mar 02 11:05:17 app/web.1:      at null._onTimeout (/app/node_modules/nforce/node_modules/faye/node/faye-node.js:1609:14) 
Mar 02 11:05:17 app/web.1:      at Timer.listOnTimeout (timers.js:92:15)

**Comment by kevinohara80** [comment]
This might be an internal Faye issue. Are you willing to bump the version and test? If it resolves the issues you can submit a PR.

**Comment by matuagarwal** [comment]
Hi @kevinohara80 , Can you bump up faye version as its causing issues while using this module.
Let me know if needed I can send a pull request for it ?
