### ISSUE TITLE
fetchAll returning max 5 records

### ISSUE THREAD

**Issue by podulator** [kevinohara80/nforce#116]
Hi, 
Thanks for this code, super useful.
querying with {query: q, fetchAll: true} only seems to return 5 rows max always, using nforce 1.4.1.
Is my implementation right?

			org.query({fetchAll: true, query: q}, function(err, resp) {
				if (err) {
					console.error("query error : " + err);
					return;
				}
				console.log("query successful");
				if (resp.records && resp.records.length > 0) {
					var numMatches = 0;
					var contacts = resp.records;
					contacts.forEach(function(contact) {
						numMatches++;
						...
					});
					var summary = "Found " + numMatches + " contacts matching '" + commandText + "': ";
				} else {
					console.log("No contacts found matching '" + commandText + "'");
				}
			});	

thanks,
mat

**Comment by kevinohara80** [comment]
Yes, your implementation looks correct. Just curious, what is your query (value of `q`)?

**Comment by podulator** [comment]
good call! i totally forgot i slung a 'limit 5' on the end for development!
thanks, and apologies for the non-issue...
mat
