### ISSUE TITLE
Does it have Approval Process methods?

### ISSUE THREAD

**Issue by weengo** [kevinohara80/nforce#121]
Hi there,

Does it provide any of the methods regarding the approval process detailed on the [Salesforce Force.com REST API Developer Guide](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/using_resources_working_with_processes.htm) ?

**Comment by kevinohara80** [comment]
Sorry for the delay on this. No, the approvals aren't currently supported. This functionality would probably best be delivered by a plugin. There is info in the reader in case you wanted to give it a shot! 😉
