### ISSUE TITLE
Inconsistent Streaming API Events

### ISSUE THREAD

**Issue by godd9170** [kevinohara80/nforce#122]
Has anyone encountered some inconsistency with receiving events after a successful PushTopic subscription? I've implemented the stream based of of @jeffdonthemic's https://github.com/jeffdonthemic/node-streaming-socketio and the day I had set it up it was working very well. However with no alterations at all, today the messages will either not come in at all, or just queue up and come through at arbitrary times.

```
var express = require('express');
var config = require('./config.js');
var nforce = require('nforce');

var app = express();
var server = require('http').Server(app);

var org = nforce.createConnection({
  clientId: config.CLIENT_ID,
  apiVersion: 'v37.0',
  clientSecret: config.CLIENT_SECRET,
  redirectUri: config.CALLBACK_URL + '/oauth/_callback',
  mode: 'multi',
  environment: config.ENVIRONMENT  // optional, sandbox or production, production default
});

org.authenticate({ username: config.USERNAME, password: config.PASSWORD }, function(err, oauth) {

  if(err) return console.log(err);
  if(!err) {
    console.log('*** Successfully connected to Salesforce ***');
    // add any logic to perform after login
  }

  // subscribe to pushtopics
  config.PUSH_TOPICS.forEach( function(pushtopic, i) {
    console.log("Subscribing To: ", i, " ", pushtopic);
    var str = org.stream({ topic : pushtopic, oauth: oauth });
    str.on('connect', function() {
      console.log('Connected to PushTopic: ', pushtopic);
    });
    str.on('error', function(err) {
      console.log('subscription error');
      console.log(err);
    });
    str.on('data', function(data) {
      data['PushTopic'] = pushtopic; //add the generating pushtopic to the data
      console.log('Received the following from pushtopic: ', pushtopic);
      console.log(data);
    });
  });
});
```

I'm inclined to blame Salesforce, but that's awfully naive. Can anyone think of what might cause this?

**Comment by jeffdonthemic** [comment]
@godd9170 I know there is a bug with v37 of the Streaming API as we are having problems with it in Workbench. I think if you switch to v36 it will work. LMK how it works out for you.

**Comment by godd9170** [comment]
That seems to have done it @jeffdonthemic! I'm happy my allegations were just. I don't suppose you've a salesforce community thread that discusses this issue you could link me to.

Thanks for the all the help.

**Comment by kevinohara80** [comment]
Thanks @jeffdonthemic
