### ISSUE TITLE
Cannot send POST/ request to ApexRest

### ISSUE THREAD

**Issue by splacentino** [kevinohara80/nforce#124]
Hello,

I am having issues using nforce while sending POST/ request.

Apex REST route:
```apex
RestResource(UrlMapping='/login/*')
global with sharing class RestLogin {
	
    @HttpPost
    global static void authentificate(String login, String password){
    }
}
```

And my nforce call to it:
```js
const login = function(request, result, next) {

  const { login, password } = request.body;

  sfService.post('login', null, { login, password })
  .then(success => {
      result.send(success)
  })
  .catch(error => {
    result.send(error)
  })
  .then(() => next());
```

sfService.post:
```js
function(uri, parameters, body) {
  return org.apexRest({ 
      uri: `${resource}/${uri}`, 
      'post', 
      parameters, 
      body
    })
}
```

The returned error:
```json
{
  "message": "Argument error, options.body."
}
```

Requesting to Salesforce using `curl` is working. What am I doing wrong ?
Nforce works perfectly when using GET/ request with parameters and empty body.

**Comment by splacentino** [comment]
Fixed by Stringifying the body:

```js
function(uri, parameters, body) {
  return org.apexRest({ 
      uri: `${resource}/${uri}`, 
      'post', 
      parameters, 
      body
    })
}
```

Is there a way to make stringifying of the body automatic ?

I do not need to stringify `parameters`.

**Comment by splacentino** [comment]
Another question while this ticket is open:

How can I send Blob (picture) file in body with nforce ?

**Comment by kevinohara80** [comment]
@splacentino yeah it could probably be done automatically. If you want to send a PR I'd be happy to review it.
