### ISSUE TITLE
Upload a blob file (picture) usign ApexRest

### ISSUE THREAD

**Issue by splacentino** [kevinohara80/nforce#125]
Hello.

I would like to upload a file, as a binary body, to Salesforce using an ApexRest route.

It works when I do it directly from `cUrl` or `postman` but I cannot do it using `nforce.apexRest()` because I do not know how to pass it has a body of the request.

Does someone have an idea ?
Thanks.

**Comment by splacentino** [comment]
Sorry I resolve this by passing `fs.readFileSync('path')` as body content, thank you.
I am still searching how to pass a body of type:
```js
{
  filename: 'name.png',
  blob: fs.readFileSync('')
}
```

**Comment by kevinohara80** [comment]
I'm not sure what you mean by "body of type". Can you explain?
