### ISSUE TITLE
Replay Events with PushTopic Streaming

### ISSUE THREAD

**Issue by thelastaghori** [kevinohara80/nforce#127]
Is it possible to extend nforce to allow for replaying of  PushTopic based streaming events?
This is a new feature that was released as part of SF's summer '16 release. 
This would be **_awesome**_!

**Comment by kevinohara80** [comment]
Yeah, that would be cool. Want to submit a PR?

**Comment by kevinohara80** [comment]
This will be resolved by the updates to the streaming api in nforce 2.0
