### ISSUE TITLE
nforce dependency on faye is out of date

### ISSUE THREAD

**Issue by kduffie** [kevinohara80/nforce#128]
package.json has a dependency on faye v1.1.0.  But faye v1.1.0 has invalid dependencies causing troubles when you run "npm list".  Faye has been update to 1.2.3 where that problem should go away.  So nforce's package should be updated to have a later dependency (or remove version dependence).

**Comment by matuagarwal** [comment]
Hi @kevinohara80 
Can you merge my PR for this
https://github.com/kevinohara80/nforce/pull/130

**Comment by kevinohara80** [comment]
Hey I'll take a look at this tomorrow and get it merged. Thanks!

**Comment by kevinohara80** [comment]
Closed by #130
