### ISSUE TITLE
How to relate two records in a many-to-many relationship?

### ISSUE THREAD

**Issue by jsitu** [kevinohara80/nforce#137]
Hi @kevinohara80 hope you are doing good. How can I relate two records in a many-to-many relationship with nforce? Right now I have two custom objects with a many-to-many relationship between them, I try to find out how to associate individual record between them. Thanks.

**Comment by kevinohara80** [comment]
Hi, this would involve a little more conversation around your code. I'd suggest posting in the Salesforce Stackexchange.
