### ISSUE TITLE
Regular Expression Denial of Service vulnerability on mime dependency

### ISSUE THREAD

**Issue by ZwaarContrast** [kevinohara80/nforce#141]
https://nodesecurity.io/advisories/535

Package: mime@1.2.11
Vulnerable: < 1.4.1 || > 2.0.0 < 2.0.3 
Patched: >= 1.4.1 < 2.0.0 || >= 2.0.3

Please upgrade the mime package

**Comment by ZwaarContrast** [comment]
Just saw this outstanding pull request:

https://github.com/kevinohara80/nforce/pull/138

**Comment by kevinohara80** [comment]
Merged. Thanks.
