### ISSUE TITLE
How can I invoke /services/data/v41.0/sobjects/StreamingChannel/0M636000000PAswCAG/push

### ISSUE THREAD

**Issue by dkoon777** [kevinohara80/nforce#146]
Your ApexRest API only handles /services/apexrest/.. kind of endpoint, I need to communicate to /services/data/v41.0/sobjects/StreamingChannel/0M636000000PAswCAG/push endpoint, how?

**Comment by kevinohara80** [comment]
There is currently not first-class support for pushing events right now. I did, however, add low-level REST methods that you can use. Prior there was only a `getUrl()` method but now there is a `putUrl()`, `postUrl()`, 'deleteUrl()` methods.

Something like this should work

```js
org.postUrl({
  url: '/services/data/v41.0/sobjects/StreamingChannel/0M636000000PAswCAG/push',
  body: { .... }
})
```

Happy to entertain a pull request to make pushing to event topics first-class. In the meantime, if you upgrade to the latest nforce you'll get these new methods.
