### ISSUE TITLE
 Prototype pollution Error during installation

### ISSUE THREAD

**Issue by karthikkornalies** [kevinohara80/nforce#155]
Hello Team,

Looks like few of dependency packages are causing a failure during the nforce package installation. Can you please advise if im missing something here.

Node Version : V6.11.1
NPM : V6.1.0

 Some vulnerabilities require your attention to resolve

#npm install nforce --save

npm WARN noderest@1.0.0 No repository field.

+ nforce@1.10.0
added 29 packages from 34 contributors and audited 1622 packages in 5.341s
found 5 vulnerabilities (1 low, 4 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nforce                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nforce > request > hawk > cryptiles > boom > hoek            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566    

Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nforce                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nforce > request > hawk > hoek                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566    

Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nforce                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nforce > request > hawk > sntp > hoek                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nforce                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nforce > lodash                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577

**Comment by pixelchutes** [comment]
I am also trying to resolve the `npm audit` vulnerability issues found in the nforce dependencies.

@kevinohara80 Is this something already on your radar or would you prefer a PR?

**Comment by ericchenmou** [comment]
+1 would be great to get @pixelchutes 's PR included to address audit issues. 

@kevinohara80 appreciate if you could let this through!
