### ISSUE TITLE
GET Request to get the BLOB object from URL 

### ISSUE THREAD

**Issue by ringoyip0901** [kevinohara80/nforce#160]
Hey there! I'm pretty new to Salesforce (**Lightning**) and have just started using nforce. Loving it! 

I have a list of URL's to a number of images stored on Salesforce's ContentDocument object. Each url is something like '/services/data/v38.0/sobjects/ContentDocument/....". I would like to get the **BLOB** data of an image via its url. Is there a method in nforce that allows developers to run a **GET request** directly to a URL in order to get the BLOB data? Normally, I think we could run a XMLHttpRequest or a fetch request, but how does it work on nforce? 

Thank you very much!

**Comment by kevinohara80** [comment]
You should try using the `getBody()` method. 

https://github.com/kevinohara80/nforce#getbodyopts-callback
