### ISSUE TITLE
How does setAttachment Work?

### ISSUE THREAD

**Issue by iyobo** [kevinohara80/nforce#174]
I'm trying to upload files up to a Record, but I can't figure out how attachments work.
The record updates, but I see no new attachments. i.e
```
  ...
  record.set('Background_Check_IP_Address__c', visitorIP);
  //upload file
  const file = await fs.readFile(`${__dirname}/myfile.png`);
  record.setAttachment('driversLicense', file);
  const response = await connect.org.update({sobject: record});
```

Where am I missing it?

**Comment by kevinohara80** [comment]
I'm not sure what type of record that is, but it must be one that supports binary data such as the `Attachment` object itself. See example...

https://github.com/kevinohara80/nforce/blob/master/examples/attachment-insert-update.js#L28
