### ISSUE TITLE
import nforce in React-js application

### ISSUE THREAD

**Issue by petersen-rex** [kevinohara80/nforce#181]
Hi All.  When executing the nforce example apps directly in Node, everything works as advertised.  When I import into a react application created with "npx create-react-app notes-app-client", and using the same parameters, it fails at the org.authenticate step with the error: "TypeError: failed to fetch".

I've been struggling with this issue all day.  Any ideas would be much appreciated!

        var org = Nforce.createConnection({
        clientId: clientID,
        clientSecret: clientSecret,
        redirectUri: 'http://localhost:3000/oauth/_callback'
        });
        
        alert("org" + JSON.stringify(org));

        org.authenticate({ username: sfuser, password: sfpass}, (err, oauth) => {
        if(err) {
            console.error('unable to authenticate to sfdc');
            alert("unable to authenticate: " + err + " oauth: " + oauth);
            throw err;
        } else { ...

**Comment by petersen-rex** [comment]
After more inspection it seems as though it is a CORS issue.  Getting this in my browser:

> Access to fetch at 'https://login.salesforce.com/services/oauth2/token' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Whitelisting localhost:3000 in Salesforce CORS settings has no effect

**Comment by petersen-rex** [comment]
Appears to be related to this issue, but I don't see a resolution:

https://github.com/kevinohara80/nforce/issues/158

**Comment by petersen-rex** [comment]
Deployed the app to a website using https and whitelisted the domain... with the same result.  Started Chrome with cors disabled, and got the following errors, "Failed to load resource: the server login.salesforce.com.. responded with status of 400 (bad request".  Unable to authenticate to sfdc: Error Unsupported_Grant_Type

**Comment by petersen-rex** [comment]
Decided to take a different approach and proxy the calls at the server, which gets around this issue.  Closing.

**Comment by charltonAthletic** [comment]
Hi @petersen-rex - can you post what your app.js code looks like? I have the same issue - I have spent ages trying to get nforce from my local host to work but, despite best efforts, keep hitting the CORS issue. 

I have hit the same issues as per this other issue: https://github.com/kevinohara80/nforce/issues/158

@kevinohara80 - is there any step by step docs on how to setup nforce with localhost? That would be very helpful. 

Thanks!
