### ISSUE TITLE
Invalid Grant - Auth failure

### ISSUE THREAD

**Issue by louisnelza** [kevinohara80/nforce#194]
My nForce integration has suddenly stopped working since yesterday.

The error message:

{
    "error": "invalid_grant",
    "error_description": "authentication failure"
}

Using the single user auth. Nforce does not have any params to set the grant type.

Going to have to migrate to JSForce.

**Comment by bacigalupe** [comment]
Any idea if it’s possible to authenticate using only Session Id? Thanks!

**Comment by louisnelza** [comment]
Had to include the securityId.
