### ISSUE TITLE
Timeout and retry option for faye.Client

### ISSUE THREAD

**Issue by chicagozer** [kevinohara80/nforce#29]
Hi, great library! When my client app is deployed into Heroku I notice that it will get disconnected if left idle for a few hours.

Right now I just hardcoded a value into the Client constructor and that seemed to solve the problem.

client = new faye.Client(endpoint, {timeout: 120, retry: 5});

Not sure if you'd ever considering adding a feature to set the option parm but I thought I'd make the suggestion. Thanks!!

**Comment by kevinohara80** [comment]
Implemented. To be released in 1.0.
