### ISSUE TITLE
Example of query streaming?

### ISSUE THREAD

**Issue by sridhar2014** [kevinohara80/nforce#51]
The documentation says that nforce supports a stream-based mechanism to handle queries with large numbers of results (say 10,000 records). But I'm relatively new to node, so it would really help to have an example of how to use this streaming feature. The example in the documentation looks like this:

```
// dataset of 50k records.
var query = 'SELECT Name, CreatedDate FROM Account ORDER BY CreatedDate DESC';
org.query({query: query, oauth: req.session.oauth }).pipe(res); // streaming all 50k records
```

But what is the "res" argument to the pipe call? Any pointers greatly appreciated.

**Comment by harpritdhanoa** [comment]
@sridhar2014,
I am getting this error when I execute your code above -
**dataStream.on ("data", function (d) {
               ^
TypeError: dataStream.on is not a function**

Did you encounter the same as well?
Any help would be appreciated.

-HD

**Comment by sridhar2014** [comment]
@harpritdhanoa The value dataStream is returned by the org.query call, and it should be an object that supports the 'on' method. You might start with a console.log (dataStream) to examine its return type, and go from there. Perhaps you're using the wrong version of nforce?

**Comment by harpritdhanoa** [comment]
@sridhar2014,
dataStream is returning as {} when I stringify it!
I'm using the latest version of nforce but am happy to investigate the version that worked for you.

I got this running using this piece of code 
`var nforce = require('nforce');
var sfuser = 'harry.dhanoa@fleetcor.com.full';
var sfpass = 'tquila22pTdCmEY84WfLrhT41Mmg0CPY';

var query = 'SELECT Id, FirstName, LastName, Email FROM Lead LIMIT 50000';

var org = nforce.createConnection({
  clientId: '3MVG9w8uXui2aB_qB4GHJ6sUeJhy.wljQUuUdrYtlZmgVG.DJY3mm0Wg7Z3.csrfwAisYDTPAF9UXPrisDwM2',
  clientSecret: 'CA27BE9F02D700871AE427910568158A98C1AD3D6BB1253C4699106B45E3CE86',
  redirectUri: 'http://localhost:3000/oauth/_callback',
  apiVersion: 'v27.0',
  environment: 'sandbox',
  mode: 'single'
});

org.authenticate({ username: sfuser, password: sfpass}, function(err, oauth) {
  if(err) {
    console.error('unable to authenticate to sfdc');
    throw err;
  } else {
    org.query({ query: query, oauth: oauth }, function(err, resp) {
      if(err) throw err;
      if(resp.records && resp.records.length) {
        console.log('Lead Count: ' +resp.records.length);
        if(resp.nextRecordsUrl) {
            queryNext(resp.nextRecordsUrl);
        }
      }
    });
  }
});

var queryNext = function(url) {
    org.getUrl(url, function(err, resp) {
      if (err) {
        return err;
      }
      if(resp.records && resp.records.length > 0) {
        console.log('Lead Count: ' +resp.records.length);
      }
      if(resp.nextRecordsUrl) {
        queryNext(resp.nextRecordsUrl);
      }
    });
}
`
