### ISSUE TITLE
Can't subscribe to multiple Streaming API topics

### ISSUE THREAD

**Issue by scottpersinger** [kevinohara80/nforce#52]
I am having trouble using 'stream' to subscribe to multiple PushTopics. In my test I am calling "stream" for two PushTopics using the same Oauth creds, and then calling stream for a third PushTopic using a different set of Oauth creds. It appears that only my last `on` handler is invoked no matter which PushTopic fires.

I am using the same `org` object, but calling stream multiple times:

```
var str = org.stream({ topic: pt_name, oauth: oauth });
str.on('data', function(data) {
  ...
}
```

Any ideas? Do I need to create separate Org objects?

**Comment by godd9170** [comment]
Hey @kevinohara80 and @scottpersinger,

I realize this one was put to bed quite some time ago, however have either of you been able to iterate through an array of topics and establish subscriptions to all on them in a tidy loop?

I'd like to DRY out the 5 events I subscribe to.

**Comment by jonathanwiesel** [comment]
@kevinohara80 I would like to subscribe to multiple push topics, how could I do it without creating separate stream variables?
