### ISSUE TITLE
List of plugins

### ISSUE THREAD

**Issue by nkint** [kevinohara80/nforce#82]
Hi! Where can I find a listo of nforce plugins?
I know that @jeffdonthemic made few plugins for tooling and chatter API, and I'm interested in analytics too. Is there a list of available plugins for nforce?
Thanks.

**Comment by jeffdonthemic** [comment]
There isn't a list that I'm aware of. Kevin may know of more.

**Comment by kevinohara80** [comment]
I've been meaning to add a list to the readme. In the future I want to have a full docs site that has a plugin directory. Stay tuned.

**Comment by kevinohara80** [comment]
Also, no known plugin yet for the analytics API. That'd be a great community contribution! ;)

I can also take a look at doing it at some point but I have some other projects I'm finishing up right now. The big one is the Metadata API plugin which is almost done.

**Comment by jeffdonthemic** [comment]
@kevinohara80 , LMK when you are done with this and I'll do a blog post on it (if you want me to). It sounds super cool!

**Comment by kevinohara80** [comment]
Sounds good!
