### ISSUE TITLE
SObject get method does not return falsy values

### ISSUE THREAD

**Issue by eliasdawson** [kevinohara80/nforce#86]
Discovered this bug when writing unit tests for my application. After setting an SObject property to false (for a checkbox in Salesforce that defaults to true). Calling the get method for that property on the object returns undefined. I traced the issue to line 28 of record.js. If the value of the property is false (or 0), it won't be returned. The value is set, just not returned by the get method.

For example:
```
var account = createSObject('Account');
account.set('Foo', false);
//account.get('Foo') === undefined
```

**Comment by eliasdawson** [comment]
I submitted a pull request with a fix. https://github.com/kevinohara80/nforce/pull/87

**Comment by kevinohara80** [comment]
Merged and closed. Thanks.
